### ISSUE TITLE
自動backupが動いていないようです

### ISSUE THREAD

**Issue by m-onda** [ayapapa/docker-alminium#37]
お世話になっています。
新たに、docker-alminiumを使用し始めました。
ちなみに、LDAP認証の問題 issue #35 は、devブランチを利用することで解決できました。有難うございます。
使用開始から、2日が経過したところですが、バックアップが自動で生成されていないことに気づきました。
コンテナにログインして調べてみたところ、cronサービスが動いていないようでした。
以下でcronサービスは動くようですので、イメージ作成時に、同様のことをやっておいた方が良さそうです。参考になれば幸いです。
```
$ sudo docker exec -it docker-alminium_ALMinium_1 bash
# apt update
# apt install cron
# service cron start
```

**Comment by m-onda** [comment]
バックアップを実験するため、cronスケジュールを修正して、自動バックアップを走らせたところ、以下のエラーとなってしまいました。コンテナに入って、手動でバックアップすると問題無くバックアップされます。cronサービスの権限などの問題とかありそうな感じですね。もっと調べてみますので、何かわかったら、また投稿します。
```
cat /mnt/alminium/log/redmine/backup.log
[Fri Mar 26 09:07:01 UTC 2021] ALMiniumのデータのバックアップを開始します。
バックアップファイル名 : /var/opt/alminium-backup/2021-03-26-09-07-01-alm-backup.tar.gz
MySQLデータベースをバックアップします。
データベースバックアップ(/var/opt/alminium-backup/db.dump)が失敗しました。
```

以下、追記：
手動でバックアップしたときのdb_option以下と、
```
-ualminium -hdb -palminium
```
自動のときのオプション（以下）が異なっていました。
```
-ualminium -hlocalhost -palminium
```
以下のようにすると、自動バックアップが動くようになりました。
ALM_DB_HOST=dbを追加しました。/bin/bashは、無くても良いのかもしれません。
```
#!/bin/bash
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
USER=root
MAILTO=root

ALM_BACKUP_CMD=/home/alm/backup
ALM_BACKUP_DIR=/var/opt/alminium-backup
ALM_BACKUP_LOG=/opt/alminium/log/backup.log

56 9 * * * root ALM_BACKUP_EXPIRY=14 ALM_DB_HOST=db /bin/bash $ALM_BACKUP_CMD $ALM_BACKUP_DIR >> $ALM_BACKUP_LOG

```

**Comment by ayapapa** [comment]
情報、有難うございます。お陰様で、対応することが出来ました。  
現在、本体(alminium)および、本プロジェクトの、devブランチにて反映されています。  この後、近いうちにmasterにマージ予定です。
